apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - issuer.yaml
  - certificate.yaml
  - ingress.yaml
  - www-redirect.yaml
images:
  - name: registry.144.91.77.245.sslip.io/grokvoice
    newName: registry.144.91.77.245.sslip.io/grokvoice
    newTag: 9c693c4bcc9180cf99e62eb1fd23be794385449b
